//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use super::sea_orm_active_enums::Place;
use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "processed_block")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub block: u64,
    pub processed_time: DateTimeUtc,
    pub last_tx_sig: Option<String>,
    pub modulo: u8,
    pub remainder: u8,
    pub status: Status,
    pub place: Place,
    pub tx_count: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
