//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "token_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub mint: String,
    pub name: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub value: f64,
    pub decimal: u8,
    pub is_skipped: u8,
    pub update_time: DateTimeUtc,
    pub creat_time: DateTime,
    pub last_updated_block: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
